Fix invalid sendto when supernode name resolution fails
Even though the supernode resolution failed, sendto was called with
and invalid socket, resulting in the following error:

ERROR: sendto failed (13) Permission denied